### ISSUE TITLE
Way Forward

### ISSUE THREAD

**Issue by ngomile** [V014/ActivityJournal#1]
So what must be done?

**Comment by ngomile** [comment]
I'm going to use ChatGPT to brainstorm some ideas as well.

**Comment by V014** [comment]
Yes please, try using Bing as well to get diverse answers, It has evolved and now its actually giving smart replys.  Sent from Mail for Windows From: Noel GomileSent: Sunday, March 12, 2023 3:32 PMTo: V014/ActivityJournalCc: SubscribedSubject: Re: [V014/ActivityJournal] Way Forward (Issue #1) I'm going to use ChatGPT to brainstorm some ideas as well.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by V014** [comment]
Okay as of now, watch the repo, because I have to do the paper work, all they want to a proposal, its supposed to be a written document but as you can see I have skipped that and gone straight to the deliverable itself. Sent from Mail for Windows From: Noel GomileSent: Sunday, March 12, 2023 3:32 PMTo: V014/ActivityJournalCc: SubscribedSubject: [V014/ActivityJournal] Way Forward (Issue #1) So what must be done?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by V014** [comment]
I dont know whats all that above

**Comment by V014** [comment]
what I can say is we need a way to make it user friendly first of all

**Comment by V014** [comment]
then we need it to perform functions, remember, functions push and pull data from the database.

**Comment by V014** [comment]
If possible, we could make a website instead, if its easier or chosen by majority.
